DROP TABLE formulario_input_template;
CREATE TABLE formulario_input_template (
  input_id int NOT NULL AUTO_INCREMENT,
  input_cuidx varchar(255) DEFAULT NULL,
  input_idx int DEFAULT NULL,
  input_status varchar(255) DEFAULT NULL,
  input_descript varchar(2000) DEFAULT NULL,
  input_type VARCHAR(255) DEFAULT NULL,
  input_name VARCHAR(255) DEFAULT NULL,
  input_value VARCHAR(255) DEFAULT NULL,
  input_placeholder VARCHAR(255) DEFAULT NULL,
  input_class VARCHAR(255) DEFAULT NULL,
  input_disabled VARCHAR(255) DEFAULT NULL,
  input_readonly VARCHAR(255) DEFAULT NULL,
  input_required VARCHAR(255) DEFAULT NULL,
  input_maxlength VARCHAR(255) DEFAULT NULL,
  input_min VARCHAR(255) DEFAULT NULL,
  input_max VARCHAR(255) DEFAULT NULL,
  input_pattern VARCHAR(255) DEFAULT NULL,
  input_size VARCHAR(255) DEFAULT NULL,
  input_autocomplete VARCHAR(255) DEFAULT NULL,
  input_autofocus VARCHAR(255) DEFAULT NULL,
  input_onclick varchar(2000) DEFAULT NULL,
  input_python_code varchar(2000) DEFAULT NULL,
  input_complement varchar(255) DEFAULT NULL,
  input_game varchar(255) DEFAULT NULL,
  input_game_type varchar(255) DEFAULT NULL,
  PRIMARY KEY (input_id)
);